# config/meta.yml

meta_product_name: "Gansky"
meta_title: "GANSKY - Les meilleurs appartements meublés"
meta_description: "Les meilleurs appartements pour habiter en colocation à Cergy Préfecture : entièrements meublés et équipées, tout-compris et réservables en ligne."
meta_image: "landing-background.jpg"
facebook_meta_title: "Les meilleures colocs' meublées de Cergy Prefecture"
facebook_meta_description: "Gansky liste les meilleurs appartements pour habiter en colocation à Cergy Préfecture : entièrements meublés et équipées, tout-compris et réservables en ligne."

